baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Serenity theme'

[params]
  description = 'Blog personal y reflexiones sobre gestión de ingeniería de software.'
  author = 'Asier Marqués'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
