baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Serenity theme'

[params]
  description = 'Blog personal y reflexiones sobre gestión de ingeniería de software.'
  author = 'Asier Marqués'
  
  [params.social]
  github = 'https://github.com/asiermarques'
  linkedin = 'https://www.linkedin.com/in/asier-marques/'
  instagram = 'https://www.instagram.com/asiermarques/'
  mail = 'mailto:asiermarques'
  bluesky = 'https://bsky.app/profile/asiermarques.com'
  x = ''

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
