name = 'serenity-hugo-theme'
license = 'MIT'
licenselink = 'https://github.com/asiermarques/serenity-hugo-theme/LICENSE'
description = 'A minimalistic theme for creating blogs and personal websites'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/asiermarques/serenity-hugo-theme'

# If you have a running demo of the theme
demosite = 'https://blog.asiermarques.com'

# Taxonomy terms
tags = ['blog', 'minimalistic']
features = []


# Add pagination configuration
paginate = 5  # Number of posts per page
paginatePath = "page"


# If the theme has a single author
[author]
  name = 'Asier Marques'
  homepage = 'https://asiermarques.com'

